import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useCallback, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";
import useUser from "./utils/useUser";

const getUsers = () => {
  return axios.get("/api/users");
};

export default function Home() {
  const router = useRouter();

  const [users, setUsers] = useState([]);

  const user = useUser();

  const fetchUsers = useCallback(async () => {
    const newUsers = (await getUsers()).data;
    setUsers(newUsers);
  }, [setUsers]);

  useEffect(() => {
    if (user === null) {
      router.push("/login");
    }
  }, [user]);

  useEffect(() => {
    fetchUsers();
  }, [fetchUsers]);

  return (
    <div className={styles.container}>
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <table>
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Role</th>
          </tr>
        </thead>
        <tbody>
          {users.map((user: any) => (
            <tr key={user.uid}>
              <td>{user.firstName}</td>
              <td>{user.lastName}</td>
              <td>{user.email}</td>
              <td>
                {user.customClaims?.admin
                  ? "Admin"
                  : user.customClaims?.staff
                  ? "Staff"
                  : "Not provided"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
