import Head from "next/head";
import React, { useEffect } from "react";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import firebaseApp from "./utils/firebase";
import Navbar from "./components/navbar";
import useUser from "./utils/useUser";
import { useRouter } from "next/router";

const auth = getAuth(firebaseApp);

export default function Login() {
  const onSubmit = async (e: any) => {
    e.preventDefault();
    const email = e.target.elements.email.value;
    const password = e.target.elements.password.value;

    await signInWithEmailAndPassword(auth, email, password);
  };

  const user = useUser();

  const router = useRouter();

  useEffect(() => {
    if (user !== null) {
      // router.push("/");
    }
  }, [user, router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
        <h3>Login</h3>
        <form onSubmit={onSubmit} className="column">
          <input name="email" placeholder="Email" type="email" />
          <input name="password" placeholder="Password" type="password" />
          <button type="submit">Login</button>
        </form>
      </div>
    </div>
  );
}
